### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Anisha7** [RobotGyal/Captian-Rainbow-Checklist#1]
Great work on these challenges! Here's some feedback to further improve your code:
- Try adding tests for edge cases. Do you have tests for your read() function? Does your program behave as expected on out-of-range indexes? Does the function properly check or uncheck an item? 
- Try adding a helper function that can mark an item as completed. Think of a symbol that could make it look checked/marked. This is a required challenge.
- You should be able to access delete and update in your select() function to allow users using the terminal prompt to delete and update items. This is a required challenge.

**Comment by RobotGyal** [comment]
Added more test functions
Added mark complete function and test
Added delete and update to select()
Added function for out of scope
